### ISSUE TITLE
Feature request: add support for github flavored markdown

### ISSUE THREAD

**Issue by agvxov** [postmodern/kramdown-man#19]
More precisely, it would be great if triple backtick code blocks were to be parsed correctly.
I don't know ruby, but i suspect, it would be relatively easy to add using [GFM Parser](https://kramdown.gettalong.org/parser/gfm.html).

**Comment by postmodern** [comment]
Considering that we're outputting to roff, and not HTML, how should GFM syntax highlighted codeblocks be handled?

**Comment by agvxov** [comment]
Not sure.
Personally, I would be happy with just the whitespace being correctly preserved.
